### ISSUE TITLE
Execute board ADC input voltage range

### ISSUE THREAD

**Issue by liuxin00738** [JFDuval/FlexSEA#2]
Hi Jean-Francois,
I am reading your papers about the FlexSEA Execute Board. It mentions that it can support 8-20 bits Sigma-Delta AD converters. I am wondering what is the input voltage range to these analog-digital converters? I checked on the PSoC's datasheet, but I could not find it. Could you help me out?

Best Regards,,
Xin Liu

**Comment by JFDuval** [comment]
Hi Xin Liu! I'm using the DelSig for the strain gauge input. Here's my configuration:

![image](https://cloud.githubusercontent.com/assets/3025794/21313274/d7587e58-c5be-11e6-9d50-c0d837db4250.png)

Also, have you looked at the new repos? https://github.com/JFDuval/flexsea-execute/tree/dev. I'm in the process of updating the documentation.

JF

**Comment by liuxin00738** [comment]
Thanks a lot!

**Comment by JFDuval** [comment]
No problem! Would you mind sharing some information about your project? You can get in touch via email.
